kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alcorset
subjects:
- kind: ServiceAccount
  name: alcorset
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: alcorset
  apiGroup: rbac.authorization.k8s.io
